"""create articles table

Revision ID: 095e856a9205
Revises: c3e48975b408
Create Date: 2025-09-19 22:29:02.033190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095e856a9205'
down_revision = 'c3e48975b408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
